# Generated by Django 3.2.7 on 2021-09-30 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_remove_agent_organsation'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='organsation',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='leads.userprofile'),
            preserve_default=False,
        ),
    ]
